import type {
  Product,
  Order,
  Customer,
  Discount,
  SalesData,
  DashboardStats,
} from '@/types'

// ─── Products ───────────────────────────────────────────────────
export const products: Product[] = [
  {
    id: 'p1',
    name: 'Nike Mercurial Superfly 9',
    slug: 'nike-mercurial-superfly-9',
    description:
      'Elite football boots engineered for explosive speed. Dynamic Fit collar and All Conditions Control texture for superior ball grip in any weather.',
    brand: 'Nike',
    sport: 'football',
    categoryId: 'cat-football',
    price: 12999,
    originalPrice: 16999,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80',
    ],
    stock: 24,
    sku: 'NK-MSF9-001',
    rating: 4.8,
    reviewCount: 234,
    badge: 'SALE',
    inStock: true,
    tags: ['boots', 'speed', 'elite', 'football'],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Upper Material', value: 'Nike Aerotrak ACC Synthetic' },
      { label: 'Sole', value: 'Carbon Fibre Soleplate' },
      { label: 'Fit', value: 'Dynamic Fit Collar' },
      { label: 'Stud Type', value: 'Firm Ground (FG)' },
      { label: 'Weight', value: '180g (UK 8.5)' },
      { label: 'Closure', value: 'Lace-up' },
      { label: 'Surface', value: 'Firm Ground' },
    ],
  },
  {
    id: 'p2',
    name: 'Adidas Predator Accuracy+',
    slug: 'adidas-predator-accuracy-plus',
    description:
      'Control-focused football boots with Controlskin upper for exceptional ball grip. Perfect for playmakers who dominate the midfield.',
    brand: 'Adidas',
    sport: 'football',
    categoryId: 'cat-football',
    price: 14499,
    images: [
      'https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?w=800&q=80',
    ],
    stock: 15,
    sku: 'AD-PA-001',
    rating: 4.7,
    reviewCount: 189,
    badge: 'BESTSELLER',
    inStock: true,
    tags: ['boots', 'control', 'premium', 'football'],
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Upper Material', value: 'Controlskin with Rubber Elements' },
      { label: 'Sole', value: 'Carbon Fibre Soleplate' },
      { label: 'Fit', value: 'Snug Laceless' },
      { label: 'Stud Type', value: 'Firm Ground (FG)' },
      { label: 'Weight', value: '195g (UK 8.5)' },
      { label: 'Closure', value: 'Laceless' },
      { label: 'Surface', value: 'Firm Ground' },
    ],
  },
  {
    id: 'p3',
    name: 'Adidas Tiro 23 Football',
    slug: 'adidas-tiro-23-football',
    description:
      'Match-quality football with thermally bonded seams for consistent flight and true touch. FIFA Basic approved.',
    brand: 'Adidas',
    sport: 'football',
    categoryId: 'cat-football',
    price: 2499,
    originalPrice: 2999,
    images: [
      'https://images.unsplash.com/photo-1553284965-5dd8352ff69a?w=800&q=80',
    ],
    stock: 60,
    sku: 'AD-T23-001',
    rating: 4.5,
    reviewCount: 312,
    badge: 'SALE',
    inStock: true,
    tags: ['ball', 'match', 'football'],
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Size', value: 'Size 5 (Match Standard)' },
      { label: 'Construction', value: 'Thermally Bonded Seamless' },
      { label: 'Panels', value: '20 Panel Design' },
      { label: 'Bladder', value: 'Butyl Bladder' },
      { label: 'Certification', value: 'FIFA Basic Approved' },
      { label: 'Material', value: 'Polyurethane Shell' },
      { label: 'Circumference', value: '68–70 cm' },
    ],
  },

  // ── Cricket ──
  {
    id: 'p4',
    name: 'SS Ton Reserve Edition Bat',
    slug: 'ss-ton-reserve-edition-bat',
    description:
      'Hand-crafted from Grade 1 English willow. Extra thick edges and a pronounced spine for maximum power. Used by international players.',
    brand: 'SS',
    sport: 'cricket',
    categoryId: 'cat-cricket',
    price: 18999,
    originalPrice: 22999,
    images: [
      'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80',
    ],
    stock: 8,
    sku: 'SS-TRE-001',
    rating: 4.9,
    reviewCount: 87,
    badge: 'LIMITED',
    inStock: true,
    tags: ['bat', 'english willow', 'premium', 'cricket'],
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Willow Grade', value: 'Grade 1 English Willow' },
      { label: 'Handle', value: 'Oval Cane Handle with Rubber Grip' },
      { label: 'Edge Thickness', value: '42mm' },
      { label: 'Spine Height', value: '68mm' },
      { label: 'Weight', value: '1.15–1.19 kg' },
      { label: 'Blade Profile', value: 'Full Profile' },
      { label: 'Recommended For', value: 'Professional / International' },
    ],
  },
  {
    id: 'p5',
    name: 'SG RSD Xtreme Batting Gloves',
    slug: 'sg-rsd-xtreme-batting-gloves',
    description:
      'Professional batting gloves with multi-colored pittards leather palm and high-density foam protection for superior comfort and control.',
    brand: 'SG',
    sport: 'cricket',
    categoryId: 'cat-cricket',
    price: 3499,
    images: [
      'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&q=80',
    ],
    stock: 30,
    sku: 'SG-RSD-001',
    rating: 4.6,
    reviewCount: 156,
    badge: 'NEW',
    inStock: true,
    tags: ['gloves', 'batting', 'protection', 'cricket'],
    createdAt: '2024-04-01T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Palm Material', value: 'Multi-colour Pittards Leather' },
      { label: 'Padding', value: 'High-Density Foam with PU Inserts' },
      { label: 'Fingers', value: 'Individually Rolled' },
      { label: 'Cuff', value: 'Extended Velcro Cuff' },
      { label: 'Sizes Available', value: 'Small, Medium, Large, XL' },
      { label: 'Hand', value: 'Right Hand Batsman' },
      { label: 'Standard', value: 'BCCI Approved' },
    ],
  },
  {
    id: 'p6',
    name: 'Kookaburra Pace 41.0 Cricket Ball',
    slug: 'kookaburra-pace-cricket-ball',
    description:
      'Premium red cricket ball with alum tanned leather and a distinctive seam for consistent swing and seam movement.',
    brand: 'Kookaburra',
    sport: 'cricket',
    categoryId: 'cat-cricket',
    price: 1299,
    originalPrice: 1599,
    images: [
      'https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?w=800&q=80',
    ],
    stock: 100,
    sku: 'KK-P41-001',
    rating: 4.4,
    reviewCount: 423,
    badge: 'SALE',
    inStock: true,
    tags: ['ball', 'leather', 'match', 'cricket'],
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Leather', value: 'Alum Tanned 4-piece Leather' },
      { label: 'Seam', value: 'Prominent 6-row Stitched Seam' },
      { label: 'Core', value: 'Multi-layer Cork Core' },
      { label: 'Weight', value: '155.9–163g (5.5–5.75 oz)' },
      { label: 'Circumference', value: '22.4–22.9 cm' },
      { label: 'Certification', value: 'ICC Approved' },
      { label: 'Usage', value: 'Match Play' },
    ],
  },

  // ── Basketball ──
  {
    id: 'p7',
    name: 'Nike LeBron NXXT Gen',
    slug: 'nike-lebron-nxxt-gen',
    description:
      "LeBron's most innovative shoe yet. AIRMAX unit and Cushlon 3.0 foam for explosive cushioning. Engineered mesh upper for lockdown fit.",
    brand: 'Nike',
    sport: 'basketball',
    categoryId: 'cat-basketball',
    price: 15999,
    originalPrice: 18999,
    images: [
      'https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=800&q=80',
    ],
    stock: 12,
    sku: 'NK-LBN-001',
    rating: 4.8,
    reviewCount: 167,
    badge: 'BESTSELLER',
    inStock: true,
    tags: ['shoes', 'basketball', 'lebron', 'nike'],
    createdAt: '2024-02-15T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Upper', value: 'Engineered Mesh with Fuse Overlays' },
      { label: 'Midsole', value: 'Cushlon 3.0 Foam + Air Max Unit' },
      { label: 'Outsole', value: 'Multi-directional Rubber' },
      { label: 'Ankle', value: 'Mid-top with Internal Heel Counter' },
      { label: 'Weight', value: '397g (US 10)' },
      { label: 'Closure', value: 'Lace-up' },
      { label: 'Surface', value: 'Indoor / Hardwood Court' },
    ],
  },
  {
    id: 'p8',
    name: 'Spalding NBA Official Game Ball',
    slug: 'spalding-nba-official-game-ball',
    description:
      'The official ball of the NBA. Full-grain Horween leather for superior feel and durability. Used in every NBA game.',
    brand: 'Spalding',
    sport: 'basketball',
    categoryId: 'cat-basketball',
    price: 8999,
    images: [
      'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80',
    ],
    stock: 20,
    sku: 'SP-NBA-001',
    rating: 4.7,
    reviewCount: 98,
    badge: 'NEW',
    inStock: true,
    tags: ['ball', 'nba', 'official', 'basketball'],
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Material', value: 'Full-grain Horween Leather' },
      { label: 'Size', value: 'Size 7 (Official NBA)' },
      { label: 'Circumference', value: '29.5 inches' },
      { label: 'Weight', value: '623g (22 oz)' },
      { label: 'Channels', value: '8 Standard Channels' },
      { label: 'Bladder', value: 'Butyl Rubber' },
      { label: 'Certification', value: 'Official NBA Game Ball' },
    ],
  },

  // ── Tennis ──
  {
    id: 'p9',
    name: 'Wilson Pro Staff RF97 Autograph',
    slug: 'wilson-pro-staff-rf97-autograph',
    description:
      "Roger Federer's signature racket. Braided graphite construction for ultimate control and feel. The choice of the greatest of all time.",
    brand: 'Wilson',
    sport: 'tennis',
    categoryId: 'cat-tennis',
    price: 21999,
    originalPrice: 25999,
    images: [
      'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800&q=80',
    ],
    stock: 6,
    sku: 'WL-RF97-001',
    rating: 4.9,
    reviewCount: 201,
    badge: 'LIMITED',
    inStock: true,
    tags: ['racket', 'federer', 'control', 'tennis'],
    createdAt: '2024-01-25T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Head Size', value: '97 sq in (626 cm²)' },
      { label: 'Length', value: '27 inches (68.6 cm)' },
      { label: 'Strung Weight', value: '340g (12 oz)' },
      { label: 'Balance', value: '31.1 cm (8 pts HL)' },
      { label: 'String Pattern', value: '16 × 19' },
      { label: 'Stiffness (RA)', value: '66' },
      { label: 'Construction', value: 'Braided Graphite / Kevlar' },
    ],
  },
  {
    id: 'p10',
    name: 'Babolat Pure Aero Rafa',
    slug: 'babolat-pure-aero-rafa',
    description:
      "Rafael Nadal's weapon of choice. FSI Spin technology and Cortex Pure Feel for maximum spin and comfort on every shot.",
    brand: 'Babolat',
    sport: 'tennis',
    categoryId: 'cat-tennis',
    price: 18499,
    images: [
      'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=800&q=80',
    ],
    stock: 10,
    sku: 'BB-PAR-001',
    rating: 4.8,
    reviewCount: 178,
    badge: 'BESTSELLER',
    inStock: true,
    tags: ['racket', 'nadal', 'spin', 'tennis'],
    createdAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Head Size', value: '100 sq in (645 cm²)' },
      { label: 'Length', value: '27 inches (68.6 cm)' },
      { label: 'Strung Weight', value: '300g (10.6 oz)' },
      { label: 'Balance', value: '32.4 cm (3 pts HL)' },
      { label: 'String Pattern', value: '16 × 19' },
      { label: 'Stiffness (RA)', value: '71' },
      { label: 'Construction', value: 'FSI Spin Carbon + Cortex Pure Feel' },
    ],
  },

  // ── Running ──
  {
    id: 'p11',
    name: 'Nike Air Zoom Pegasus 40',
    slug: 'nike-air-zoom-pegasus-40',
    description:
      'The workhorse of Nike running shoes. React foam midsole and Air Zoom unit for responsive cushioning mile after mile.',
    brand: 'Nike',
    sport: 'running',
    categoryId: 'cat-running',
    price: 9999,
    originalPrice: 11999,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
    ],
    stock: 35,
    sku: 'NK-AZP40-001',
    rating: 4.7,
    reviewCount: 445,
    badge: 'SALE',
    inStock: true,
    tags: ['shoes', 'running', 'zoom', 'nike'],
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Upper', value: 'Engineered Mesh' },
      { label: 'Midsole', value: 'React Foam + Air Zoom Unit' },
      { label: 'Outsole', value: 'Waffle Pattern Rubber' },
      { label: 'Drop', value: '10mm' },
      { label: 'Weight', value: "284g (Men's US 10)" },
      { label: 'Closure', value: 'Lace-up' },
      { label: 'Best For', value: 'Daily Training / Road Running' },
    ],
  },
  {
    id: 'p12',
    name: 'Garmin Forerunner 955 Solar',
    slug: 'garmin-forerunner-955-solar',
    description:
      'GPS running smartwatch with solar charging. Training readiness, HRV status, and race predictor for serious runners.',
    brand: 'Garmin',
    sport: 'running',
    categoryId: 'cat-running',
    price: 54999,
    originalPrice: 59999,
    images: [
      'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&q=80',
    ],
    stock: 5,
    sku: 'GR-F955S-001',
    rating: 4.9,
    reviewCount: 134,
    badge: 'NEW',
    inStock: true,
    tags: ['watch', 'gps', 'solar', 'running'],
    createdAt: '2024-04-10T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Display', value: '1.3" MIP Sunlight-readable' },
      { label: 'Battery Life', value: 'Up to 20 days (Solar: 42 days)' },
      { label: 'GPS Modes', value: 'GPS, GLONASS, Galileo, MultiGNSS' },
      { label: 'Water Rating', value: '5 ATM' },
      { label: 'Weight', value: '53g' },
      { label: 'Connectivity', value: 'Bluetooth, ANT+, Wi-Fi' },
      { label: 'Health Sensors', value: 'HRV, SpO2, Skin Temp, HRM' },
    ],
  },

  // ── Swimming ──
  {
    id: 'p13',
    name: 'Speedo Fastskin Pure Focus Goggles',
    slug: 'speedo-fastskin-pure-focus-goggles',
    description:
      'Elite competition goggles with panoramic lens for wide field of view. Hydrodynamic design reduces drag for faster times.',
    brand: 'Speedo',
    sport: 'swimming',
    categoryId: 'cat-swimming',
    price: 3999,
    images: [
      'https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=800&q=80',
    ],
    stock: 25,
    sku: 'SP-FSPF-001',
    rating: 4.6,
    reviewCount: 89,
    badge: 'NEW',
    inStock: true,
    tags: ['goggles', 'competition', 'swimming'],
    createdAt: '2024-03-15T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Lens Type', value: 'Panoramic Curved Lens' },
      { label: 'UV Protection', value: 'UV 400' },
      { label: 'Anti-Fog', value: 'Yes' },
      { label: 'Gasket', value: 'Low-profile Hydrodynamic Seal' },
      { label: 'Strap', value: 'Dual Silicone Strap' },
      { label: 'Nose Bridge', value: 'Adjustable' },
      { label: 'Best For', value: 'Competition / Elite Training' },
    ],
  },

  // ── Boxing ──
  {
    id: 'p14',
    name: 'Everlast Pro Style Training Gloves',
    slug: 'everlast-pro-style-training-gloves',
    description:
      'Premium synthetic leather boxing gloves with Evercool moisture management lining. Perfect for bag work, pad work, and sparring.',
    brand: 'Everlast',
    sport: 'boxing',
    categoryId: 'cat-boxing',
    price: 4499,
    originalPrice: 5499,
    images: [
      'https://images.unsplash.com/photo-1552072092-7f9b8d63efcb?w=800&q=80',
    ],
    stock: 18,
    sku: 'EV-PST-001',
    rating: 4.5,
    reviewCount: 267,
    badge: 'SALE',
    inStock: true,
    tags: ['gloves', 'training', 'boxing'],
    createdAt: '2024-02-05T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Material', value: 'Premium Synthetic Leather' },
      { label: 'Lining', value: 'Evercool Moisture Management' },
      { label: 'Closure', value: 'Hook & Loop Velcro Wrist Strap' },
      { label: 'Padding', value: 'Multi-layer Foam' },
      { label: 'Weight Options', value: '8oz, 10oz, 12oz, 14oz, 16oz' },
      { label: 'Best For', value: 'Bag Work, Pad Work, Sparring' },
      { label: 'Thumb', value: 'Attached Thumb Safety' },
    ],
  },

  // ── Cycling ──
  {
    id: 'p15',
    name: 'Trek Domane AL 2 Road Bike',
    slug: 'trek-domane-al-2-road-bike',
    description:
      'Endurance road bike with Alpha Aluminum frame and carbon fork. IsoSpeed decoupler smooths out road vibration for all-day comfort.',
    brand: 'Trek',
    sport: 'cycling',
    categoryId: 'cat-cycling',
    price: 89999,
    originalPrice: 99999,
    images: [
      'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800&q=80',
    ],
    stock: 3,
    sku: 'TK-DA2-001',
    rating: 4.8,
    reviewCount: 45,
    badge: 'SALE',
    inStock: true,
    tags: ['bike', 'road', 'endurance', 'cycling'],
    createdAt: '2024-03-20T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
    specs: [
      { label: 'Frame', value: 'Alpha Aluminum with IsoSpeed Decoupler' },
      { label: 'Fork', value: 'Full Carbon' },
      { label: 'Groupset', value: 'Shimano Claris R2000' },
      { label: 'Gears', value: '16 Speed (2×8)' },
      { label: 'Brakes', value: 'Rim Brakes' },
      { label: 'Wheel Size', value: '700c' },
      { label: 'Sizes Available', value: '47, 50, 52, 54, 56, 58, 60, 62 cm' },
    ],
  },
]

// ─── Orders ─────────────────────────────────────────────────────
export const orders: Order[] = [
  {
    id: 'ord-001',
    orderNumber: 'AS-847291',
    customerId: 'cust-001',
    customerName: 'Arjun Sharma',
    customerEmail: 'arjun.sharma@email.com',
    items: [
      {
        productId: 'p1',
        productName: 'Nike Mercurial Superfly 9',
        sku: 'NK-MSF9-001',
        quantity: 1,
        price: 12999,
        total: 12999,
      },
      {
        productId: 'p3',
        productName: 'Adidas Tiro 23 Football',
        sku: 'AD-T23-001',
        quantity: 2,
        price: 2499,
        total: 4998,
      },
    ],
    status: 'delivered',
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    shippingAddress: {
      name: 'Arjun Sharma',
      phone: '9876543210',
      line1: '42 MG Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      country: 'India',
    },
    subtotal: 17997,
    discount: 0,
    shipping: 0,
    tax: 3240,
    total: 21237,
    source: 'website',
    createdAt: '2024-05-10T14:30:00Z',
    updatedAt: '2024-05-14T10:00:00Z',
  },
  {
    id: 'ord-002',
    orderNumber: 'AS-847292',
    customerId: 'cust-002',
    customerName: 'Priya Patel',
    customerEmail: 'priya.patel@email.com',
    items: [
      {
        productId: 'p9',
        productName: 'Wilson Pro Staff RF97 Autograph',
        sku: 'WL-RF97-001',
        quantity: 1,
        price: 21999,
        total: 21999,
      },
    ],
    status: 'shipped',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    shippingAddress: {
      name: 'Priya Patel',
      phone: '9765432109',
      line1: '15 Linking Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400050',
      country: 'India',
    },
    subtotal: 21999,
    discount: 2000,
    shipping: 0,
    tax: 3600,
    total: 23599,
    source: 'website',
    createdAt: '2024-05-18T09:15:00Z',
    updatedAt: '2024-05-20T16:00:00Z',
  },
  {
    id: 'ord-003',
    orderNumber: 'AS-847293',
    customerId: 'cust-003',
    customerName: 'Rohit Verma',
    customerEmail: 'rohit.verma@email.com',
    items: [
      {
        productId: 'p4',
        productName: 'SS Ton Reserve Edition Bat',
        sku: 'SS-TRE-001',
        quantity: 1,
        price: 18999,
        total: 18999,
      },
      {
        productId: 'p5',
        productName: 'SG RSD Xtreme Batting Gloves',
        sku: 'SG-RSD-001',
        quantity: 1,
        price: 3499,
        total: 3499,
      },
      {
        productId: 'p6',
        productName: 'Kookaburra Pace 41.0 Cricket Ball',
        sku: 'KK-P41-001',
        quantity: 3,
        price: 1299,
        total: 3897,
      },
    ],
    status: 'processing',
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    shippingAddress: {
      name: 'Rohit Verma',
      phone: '9654321098',
      line1: '8 Civil Lines',
      city: 'Delhi',
      state: 'Delhi',
      pincode: '110054',
      country: 'India',
    },
    subtotal: 26395,
    discount: 0,
    shipping: 0,
    tax: 4751,
    total: 31146,
    source: 'website',
    createdAt: '2024-05-22T11:45:00Z',
    updatedAt: '2024-05-22T12:00:00Z',
  },
  {
    id: 'ord-004',
    orderNumber: 'AS-847294',
    customerId: 'cust-004',
    customerName: 'Sneha Iyer',
    customerEmail: 'sneha.iyer@email.com',
    items: [
      {
        productId: 'p11',
        productName: 'Nike Air Zoom Pegasus 40',
        sku: 'NK-AZP40-001',
        quantity: 1,
        price: 9999,
        total: 9999,
      },
      {
        productId: 'p12',
        productName: 'Garmin Forerunner 955 Solar',
        sku: 'GR-F955S-001',
        quantity: 1,
        price: 54999,
        total: 54999,
      },
    ],
    status: 'pending',
    paymentStatus: 'pending',
    paymentMethod: 'cod',
    shippingAddress: {
      name: 'Sneha Iyer',
      phone: '9543210987',
      line1: '22 Anna Salai',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600002',
      country: 'India',
    },
    subtotal: 64998,
    discount: 5000,
    shipping: 0,
    tax: 10800,
    total: 70798,
    source: 'website',
    createdAt: '2024-05-25T16:20:00Z',
    updatedAt: '2024-05-25T16:20:00Z',
  },
  {
    id: 'ord-005',
    orderNumber: 'AS-847295',
    customerId: 'cust-005',
    customerName: 'Vikram Singh',
    customerEmail: 'vikram.singh@email.com',
    items: [
      {
        productId: 'p7',
        productName: 'Nike LeBron NXXT Gen',
        sku: 'NK-LBN-001',
        quantity: 1,
        price: 15999,
        total: 15999,
      },
      {
        productId: 'p8',
        productName: 'Spalding NBA Official Game Ball',
        sku: 'SP-NBA-001',
        quantity: 1,
        price: 8999,
        total: 8999,
      },
    ],
    status: 'confirmed',
    paymentStatus: 'paid',
    paymentMethod: 'card',
    shippingAddress: {
      name: 'Vikram Singh',
      phone: '9432109876',
      line1: '5 Park Street',
      city: 'Kolkata',
      state: 'West Bengal',
      pincode: '700016',
      country: 'India',
    },
    subtotal: 24998,
    discount: 0,
    shipping: 0,
    tax: 4500,
    total: 29498,
    source: 'pos',
    createdAt: '2024-05-26T10:00:00Z',
    updatedAt: '2024-05-26T10:30:00Z',
  },
]

// ─── Customers ──────────────────────────────────────────────────
export const customers: Customer[] = [
  {
    id: 'cust-001',
    name: 'Arjun Sharma',
    email: 'arjun.sharma@email.com',
    phone: '9876543210',
    totalOrders: 5,
    totalSpent: 87450,
    tags: ['vip', 'football'],
    createdAt: '2023-11-10T10:00:00Z',
  },
  {
    id: 'cust-002',
    name: 'Priya Patel',
    email: 'priya.patel@email.com',
    phone: '9765432109',
    totalOrders: 3,
    totalSpent: 54230,
    tags: ['tennis'],
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'cust-003',
    name: 'Rohit Verma',
    email: 'rohit.verma@email.com',
    phone: '9654321098',
    totalOrders: 8,
    totalSpent: 143200,
    tags: ['vip', 'cricket'],
    createdAt: '2023-09-20T10:00:00Z',
  },
  {
    id: 'cust-004',
    name: 'Sneha Iyer',
    email: 'sneha.iyer@email.com',
    phone: '9543210987',
    totalOrders: 2,
    totalSpent: 70798,
    tags: ['running'],
    createdAt: '2024-03-05T10:00:00Z',
  },
  {
    id: 'cust-005',
    name: 'Vikram Singh',
    email: 'vikram.singh@email.com',
    phone: '9432109876',
    totalOrders: 6,
    totalSpent: 98760,
    tags: ['basketball', 'vip'],
    createdAt: '2023-12-01T10:00:00Z',
  },
]

// ─── Discounts ──────────────────────────────────────────────────
export const discounts: Discount[] = [
  {
    id: 'disc-001',
    code: 'APEX10',
    type: 'percentage',
    value: 10,
    minOrderAmount: 2000,
    maxUses: 500,
    usedCount: 234,
    startsAt: '2024-01-01T00:00:00Z',
    expiresAt: '2024-12-31T23:59:59Z',
    isActive: true,
  },
  {
    id: 'disc-002',
    code: 'FLAT500',
    type: 'fixed',
    value: 500,
    minOrderAmount: 3000,
    maxUses: 200,
    usedCount: 89,
    startsAt: '2024-04-01T00:00:00Z',
    expiresAt: '2024-06-30T23:59:59Z',
    isActive: true,
  },
  {
    id: 'disc-003',
    code: 'FREESHIP',
    type: 'free_shipping',
    value: 0,
    usedCount: 456,
    startsAt: '2024-01-01T00:00:00Z',
    isActive: true,
  },
]

// ─── Sales Data ─────────────────────────────────────────────────
export const salesData: SalesData[] = [
  { date: '2024-05-01', revenue: 45230, orders: 12, avgOrderValue: 3769 },
  { date: '2024-05-02', revenue: 38900, orders: 9, avgOrderValue: 4322 },
  { date: '2024-05-03', revenue: 62100, orders: 15, avgOrderValue: 4140 },
  { date: '2024-05-04', revenue: 29800, orders: 8, avgOrderValue: 3725 },
  { date: '2024-05-05', revenue: 71500, orders: 18, avgOrderValue: 3972 },
  { date: '2024-05-06', revenue: 88200, orders: 22, avgOrderValue: 4009 },
  { date: '2024-05-07', revenue: 54300, orders: 14, avgOrderValue: 3879 },
  { date: '2024-05-08', revenue: 41200, orders: 11, avgOrderValue: 3745 },
  { date: '2024-05-09', revenue: 67800, orders: 17, avgOrderValue: 3988 },
  { date: '2024-05-10', revenue: 93400, orders: 24, avgOrderValue: 3892 },
  { date: '2024-05-11', revenue: 78600, orders: 20, avgOrderValue: 3930 },
  { date: '2024-05-12', revenue: 55100, orders: 13, avgOrderValue: 4238 },
  { date: '2024-05-13', revenue: 44700, orders: 11, avgOrderValue: 4064 },
  { date: '2024-05-14', revenue: 61300, orders: 16, avgOrderValue: 3831 },
]

// ─── Dashboard Stats ─────────────────────────────────────────────
export const dashboardStats: DashboardStats = {
  totalRevenue: 8743200,
  totalOrders: 2341,
  totalCustomers: 1876,
  totalProducts: 15,
  revenueChange: 18.4,
  ordersChange: 12.7,
  customersChange: 24.1,
  productsChange: 5.3,
}

// ─── Featured / Homepage ─────────────────────────────────────────
export const featuredProducts = products.filter((p) =>
  ['p1', 'p4', 'p7', 'p9', 'p11', 'p14'].includes(p.id),
)

export const newArrivals = products.filter((p) => p.badge === 'NEW')

export const bestSellers = products.filter((p) => p.badge === 'BESTSELLER')

export const saleProducts = products.filter((p) => p.badge === 'SALE')

export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug)

export const getProductsBySlug = (sport: string) =>
  products.filter((p) => p.sport === sport)

export const getRelatedProducts = (product: Product, limit = 4) =>
  products
    .filter((p) => p.sport === product.sport && p.id !== product.id)
    .slice(0, limit)
